-- Query 1 (Llamados Competencia - Prefijo 809)
CREATE OR REPLACE TABLE `analytics-project-dev.churn_reporting.BT_LLAMADAS_ENTRANTES_ULT40_DIAS_V4` AS

WITH llamadas_ult_40d AS (
  SELECT
    FECHA_EVENTO AS FECHA_LLAMADA,
    DATE(PARSE_DATE('%Y%m%d', CAST(FECHA_EVENTO AS STRING))) AS FECHA_LLAMADA_DATE,
    NUMERO_ORIGEN,
    RIGHT(REGEXP_REPLACE(CAST(NUMERO_ORIGEN AS STRING), r'\D', ''), 9) AS NUMERO_ORIGEN_9DIG,
    NUMERO_DESTINO,
    RIGHT(REGEXP_REPLACE(CAST(NUMERO_DESTINO AS STRING), r'\D', ''), 9) AS NUMERO_DESTINO_9DIG,
    DURACION,
    CASE
      WHEN DURACION <=5 THEN '<5>'
      WHEN DURACION BETWEEN 6 AND 10 THEN '6s-10s'
      WHEN DURACION BETWEEN 10 AND 60 THEN '10s-1min'
      WHEN DURACION BETWEEN 61 AND 300 THEN '1-5min'
      ELSE '>5min'
    END AS TRAMO_DURACION,
    CASE WHEN DURACION < 6 THEN 0 ELSE 1 END AS CONTACTADO,
    CASE WHEN UNIDAD ='EVENT' THEN 0 ELSE 1 END AS VISIBLE,
    CASE
      WHEN STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '56809123')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '809123')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '562809123') THEN 'Entel'
      WHEN STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '56809038')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '809038')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '562809038') THEN 'WOM'
      WHEN STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '56809005')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '809005')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '562809005')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '809007')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '56809007')
        OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '562809007') THEN 'Movistar'
--    WHEN STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '56809036')
--      OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '809036')
--      OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '562809036') THEN 'Mundo'
      ELSE 'Otros'
    END AS EMPRESA_ORIGEN,
    CAST(dt AS DATE) AS dt_llamada
  FROM `datalake-project-dev.usage_curated.mobile_v002_voice_traffic`
  WHERE CAST(dt AS DATE) BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 39 DAY)
                             AND CURRENT_DATE()
    AND (
      STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '56809')
      OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '809')
      OR STARTS_WITH(CAST(NUMERO_ORIGEN AS STRING), '562809')
    )
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY FECHA_EVENTO, NUMERO_ORIGEN_9DIG, NUMERO_DESTINO_9DIG, DURACION
    ORDER BY dt DESC
  ) = 1
),

cartera_filtrada AS (
  SELECT
    PCS,
    RIGHT(REGEXP_REPLACE(CAST(PCS AS STRING), r'\D', ''), 9) AS PCS_9DIG,
    RUT,
    CAST(dt AS DATE) AS dt_cartera,
    PERIODO_PARQUE,
    ROW_NUMBER() OVER(PARTITION BY RIGHT(REGEXP_REPLACE(CAST(PCS AS STRING), r'\D', ''), 8)
                      ORDER BY CAST(dt AS DATE) DESC) AS rn
  FROM `datalake-project-dev.account_info_raw.mobile_v001_postpaid_portfolio`
  WHERE CAST(dt AS DATE) <= DATE_SUB(CURRENT_DATE(), INTERVAL 2 DAY)
    AND SUB_CLAS_CRP = 'PERSONA'
)

SELECT
  l.FECHA_LLAMADA,
  l.FECHA_LLAMADA_DATE,
  l.NUMERO_ORIGEN_9DIG,
  l.NUMERO_DESTINO_9DIG,
  l.EMPRESA_ORIGEN,
  l.DURACION,
  l.TRAMO_DURACION,
  l.CONTACTADO,
  l.VISIBLE,
  l.dt_llamada,
  c.RUT,
  c.PERIODO_PARQUE,
  c.dt_cartera,
FROM llamadas_ult_40d l
LEFT JOIN cartera_filtrada c
  ON l.NUMERO_DESTINO_9DIG = c.PCS_9DIG
 AND (
       (l.FECHA_LLAMADA_DATE < DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AND l.FECHA_LLAMADA_DATE = c.dt_cartera)
    OR (l.FECHA_LLAMADA_DATE = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AND c.rn = 1)
     )
WHERE c.RUT IS NOT NULL
ORDER BY FECHA_LLAMADA, NUMERO_ORIGEN;
