-- Query 2 (Portabilidad y tasas de PortOut aperturada por Segmento de Duración)

CREATE OR REPLACE TABLE `analytics-project-dev.churn_reporting.BT_PORT_OUT_LLAMADAS_ENTR_V4` AS

WITH llamadas AS (
  SELECT
    FECHA_LLAMADA_DATE,
    TRAMO_DURACION,
    NUMERO_DESTINO_9DIG,
    RUT
  FROM
    `analytics-project-dev.churn_reporting.BT_LLAMADAS_ENTRANTES_ULT40_DIAS_V4`
    WHERE CONTACTADO = 1
),

portabilidad AS (
  SELECT
    RIGHT(REGEXP_REPLACE(CAST(PCS AS STRING), r'\D', ''), 9) AS PCS_9DIG,
    DIA_PORT_DATE
  FROM
    `analytics-project-dev.semantic_layer_dev.BT_PRT_PORTABILIDAD_INDUSTRIA`
),

-- Cruce de llamadas con portabilidad a 5 días
cruce AS (
  SELECT
    l.FECHA_LLAMADA_DATE,
    l.TRAMO_DURACION,
    l.NUMERO_DESTINO_9DIG,
    l.RUT,
    p.DIA_PORT_DATE,
    CASE
      WHEN p.DIA_PORT_DATE BETWEEN l.FECHA_LLAMADA_DATE AND DATE_ADD(l.FECHA_LLAMADA_DATE, INTERVAL 5 DAY)
        THEN 1 ELSE 0
    END AS SE_PORTO_5D
  FROM
    llamadas l
  LEFT JOIN
    portabilidad p
  ON
    l.NUMERO_DESTINO_9DIG = p.PCS_9DIG
)

SELECT
  FECHA_LLAMADA_DATE,
  TRAMO_DURACION,
  COUNT(DISTINCT NUMERO_DESTINO_9DIG) AS Q_PCS_CONTACTADOS,
  COUNT(DISTINCT CASE WHEN SE_PORTO_5D = 1 THEN NUMERO_DESTINO_9DIG END) AS Q_PCS_PORTADOS_5D,
  COUNT(DISTINCT RUT) AS Q_RUT_CONTACTADOS,
  COUNT(DISTINCT CASE WHEN SE_PORTO_5D = 1 THEN RUT END) AS Q_RUT_PORTADOS,
  SAFE_DIVIDE(
    COUNT(DISTINCT CASE WHEN SE_PORTO_5D = 1 THEN NUMERO_DESTINO_9DIG END),
    COUNT(DISTINCT NUMERO_DESTINO_9DIG)
  ) AS PCS_PORTABILIDAD_PCS,
  SAFE_DIVIDE(
    COUNT(DISTINCT CASE WHEN SE_PORTO_5D = 1 THEN RUT END),
    COUNT(DISTINCT RUT)
  ) AS PCS_PORTABILIDAD_RUT
FROM
  cruce
GROUP BY
  FECHA_LLAMADA_DATE, TRAMO_DURACION
ORDER BY
  FECHA_LLAMADA_DATE, TRAMO_DURACION;
