-- Query 3 (Portabilidad y tasas de PortOut aperturada por Segmento de Duración y Empresa de Origen de la llamada)

CREATE OR REPLACE TABLE `analytics-project-dev.churn_reporting.BT_PORT_OUT_LLAMADAS_ENTR_EMPRESAS_V4` AS

WITH llamadas AS (
  SELECT
    FECHA_LLAMADA_DATE,
    TRAMO_DURACION,
    EMPRESA_ORIGEN,
    NUMERO_DESTINO_9DIG,
    RUT,
    SAFE_CAST(SUBSTR(NUMERO_DESTINO_9DIG, 1, 9) AS STRING) AS PCS
  FROM
    `analytics-project-dev.churn_reporting.BT_LLAMADAS_ENTRANTES_ULT40_DIAS_V4`
),

portabilidad_5d AS (
  SELECT
    PCS,
    RIGHT(REGEXP_REPLACE(CAST(PCS AS STRING), r'\D', ''), 9) AS PCS_9DIG,
    DIA_PORT_DATE
  FROM
    `analytics-project-dev.semantic_layer_dev.BT_PRT_PORTABILIDAD_INDUSTRIA`
),

llamadas_con_porta AS (
  SELECT
    l.FECHA_LLAMADA_DATE,
    l.TRAMO_DURACION,
    l.EMPRESA_ORIGEN,
    l.PCS,
    l.RUT,
    CASE
      WHEN p.PCS IS NOT NULL
           AND p.DIA_PORT_DATE BETWEEN l.FECHA_LLAMADA_DATE
                                   AND DATE_ADD(l.FECHA_LLAMADA_DATE, INTERVAL 5 DAY)
      THEN 1 ELSE 0
    END AS SE_PORTO
  FROM llamadas l
  LEFT JOIN portabilidad_5d p
    ON l.PCS = p.PCS_9DIG
),

resumen AS (
  SELECT
    FECHA_LLAMADA_DATE,
    TRAMO_DURACION,
    EMPRESA_ORIGEN,
    COUNT(DISTINCT PCS) AS PCS_CONTACTADOS,
    COUNT(DISTINCT CASE WHEN SE_PORTO = 1 THEN PCS END) AS PCS_PORTADOS_5D,
    COUNT(DISTINCT RUT) AS RUT_CONTACTADOS,
    COUNT(DISTINCT CASE WHEN se_porto = 1 THEN RUT END) AS RUT_PORTADOS_5D
  FROM llamadas_con_porta
  GROUP BY FECHA_LLAMADA_DATE, TRAMO_DURACION, EMPRESA_ORIGEN
),

fechas AS (
  SELECT DISTINCT FECHA_LLAMADA_DATE
  FROM llamadas
),

segmentos AS (
  SELECT DISTINCT TRAMO_DURACION FROM llamadas
),

empresas AS (
  SELECT DISTINCT EMPRESA_ORIGEN FROM llamadas
),

calendarizado AS (
  SELECT
    f.FECHA_LLAMADA_DATE,
    s.TRAMO_DURACION,
    e.EMPRESA_ORIGEN
  FROM fechas f
  CROSS JOIN segmentos s
  CROSS JOIN empresas e
)

SELECT
  c.FECHA_LLAMADA_DATE,
  c.TRAMO_DURACION,
  c.EMPRESA_ORIGEN,
  COALESCE(r.PCS_CONTACTADOS, 0) AS PCS_CONTACTADOS,
  COALESCE(r.PCS_PORTADOS_5D, 0) AS PCS_PORTADOS_5D,
  COALESCE(r.RUT_CONTACTADOS, 0) AS RUT_CONTACTADOS,
  COALESCE(r.RUT_PORTADOS_5D, 0) AS RUT_PORTADOS_5D,
  SAFE_DIVIDE(COALESCE(r.PCS_PORTADOS_5D, 0), NULLIF(r.PCS_CONTACTADOS, 0)) AS PCT_PORTABILIDAD_PCS,
  SAFE_DIVIDE(COALESCE(r.RUT_PORTADOS_5D, 0), NULLIF(r.RUT_CONTACTADOS, 0)) AS PCT_PORTABILIDAD_RUT
FROM calendarizado c
LEFT JOIN resumen r
  ON c.FECHA_LLAMADA_DATE = r.FECHA_LLAMADA_DATE
 AND c.TRAMO_DURACION = r.TRAMO_DURACION
 AND c.EMPRESA_ORIGEN = r.EMPRESA_ORIGEN
ORDER BY FECHA_LLAMADA_DATE, TRAMO_DURACION, EMPRESA_ORIGEN;
